### ISSUE TITLE
2016.5.25 reading assignment

### ISSUE THREAD

**Issue by deshansun** [deshansun/Never-too-late-to-learn#1]
@ontouchstart

> Today's reading assignment:
> Find your hometown （where you grew up) and where you live now entries on 
> [http://wikipedia.org](http://wikipedia.org) and share the link with us
> What is your biggest surprise and discovery about your hometown after reading about it on wikipedia? Share with us.
> This is a reading and writing class, not a searching and sharing links class.

**Comment by deshansun** [comment]
I'm a native of Beijing.
Beijing is not the most populous city in the world, and is ranked third after Shanghai and Karachi. 
Beijing is not the biggest city in China. Shanghai is the biggest.

[Beijing](https://en.wikipedia.org/wiki/Beijing)

**Comment by ghost** [comment]
Perfect!

:+1:

**Comment by ghost** [comment]
You might want to add links to the other cities mentioned here

> Beijing is not the most populous city in the world, and is ranked third after [Shanghai](https://en.wikipedia.org/wiki/Shanghai) and [Karachi](https://en.wikipedia.org/wiki/Karachi). 
> Beijing is not the biggest city in China. Shanghai is the biggest.

This powerful idea is called [hypertext](https://en.wikipedia.org/wiki/Hypertext).

**Comment by csgashine** [comment]
I am here!

**Comment by xdq73** [comment]
I am here

**Comment by xdq73** [comment]
My hometown is [WeiHai](https://en.wikipedia.org/wiki/Weihai) Shandong
